# Nombre del workflow (aparecer치 en la GUI)
name: hello-world
# Cu치ndo se ejecuta: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on: push
# Listado de jobs
jobs:
  # ID del job. Cada job se ejecuta en una m치quina nueva
 Generar-Imagen:
    # Tipo de m치quina. Puede ser de Github o un self-hosted runner:
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        run: echo "Hello World!"
  
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.13.1' # The Go version to download (if necessary) and use.

      - name: Test test
        run: go test ./...

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platform: linux/amd64
          push: false
          tags: ghcr.io/tesudacochino/mirepo:${{github.sha}}

